on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up env
      run: |
        curl https://sh.rustup.rs -sSf | sh
        source $HOME/.cargo/env
        cargo install cargo-update
        cargo install --vers "^0.3" mdbook
        cargo install-update -a
    - name: Write the book
      run: mdbook build
    - name: Publish
      run: |
        printenv | grep GITHUB
        git worktree add /tmp/book gh-pages
        rm -rf /tmp/book/* /tmp/book/
        cp -rf book/* /tmp/book
        cd /tmp/book
        # git config --global user.email "action@github.com"
        # git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Update book"
        git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${REPOSITORY}.git" HEAD:gh-pages
